### ISSUE TITLE
redis dedicated keep dump.rdb file during upgrade

### ISSUE THREAD

**Issue by gcordierOrange** [orange-cloudfoundry/paas-templates#1018]
### Expected behavior

* As a paas-templates operator | marketplace user | paas-templates maintainer
* In order to stop / start redis
* I need to have a clean redis or a redis with the keys before stop

### Observed behavior
Before install v46, redis make a save into dump.rdb with the content of the cache
Since v46, no more backup are done, but the dump.rdb file is always present with the old keys (before v46)
When when stop / start redis, the process reload the dump.rdb file with old keys.
This old keys can create some failure for project, for example, we reload old credential.
I think, since v46 no backup are done (no configuration)

### Affected releases

* v46
* earlier versions

**Comment by yellowred-orange** [comment]
As it is indicated in [*CHANGELOG.md*](https://github.com/orange-cloudfoundry/redis-orange/blob/master/CHANGELOG.md), since v1.0.2 (i.e. v46):

> RDB persistence was enabled by default. Since this release, no persistence (i.e. no RDB neither AOF)is the default and, by default, diskless is used for replication.

When you upgrade from a previous release to v1.0.2:

  - If you let the v1.0.2 default settings (i.e. with no persistence) and you don't destroy previous VMs or you use persistent disks, you need to delete existing RDB or AOF files before upgrading.
  - If you want to reuse yours previous persistent settings, you should instruct them in your v1.0.2's deployment manifest.
