### ISSUE TITLE
recreate from scratch openldap data from shield backup

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#1107]
### Expected behavior

test 1 : delete ns openldap , run errand to recreate openldap ,restore from shield backup

context : now openldap use deployment and not statefulset K8S object
what we see:
     pvc is recreated, pv land on agent2 (it was previously on agent 1)  and doesn't have same name (it's because we use deployment instead of statefulset)

```
 kubectl get pvc -n openldap 
NAME                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
ldap-config-ldap-0   Bound    pvc-96d5ecd5-d57e-41da-a050-3becb272340c   10Mi       RWO            local-path     36m
ldap-certs-ldap-0    Bound    pvc-47bc0b7b-4758-4872-837d-7dcf0845bc19   10Mi       RWO            local-path     36m
ldap-data-ldap-0     Bound    pvc-be1f270c-5699-4b50-a904-40a777e284ec   1Gi        RWO            local-path     36m

```
```
kubectl describe pv pvc-be1f270c-5699-4b50-a904-40a777e284ec 
Name:              pvc-be1f270c-5699-4b50-a904-40a777e284ec
Labels:            <none>
Annotations:       pv.kubernetes.io/provisioned-by: rancher.io/local-path
Finalizers:        [kubernetes.io/pv-protection]
StorageClass:      local-path
Status:            Bound
Claim:             openldap/ldap-data-ldap-0
Reclaim Policy:    Delete
Access Modes:      RWO
VolumeMode:        Filesystem
Capacity:          1Gi
Node Affinity:     
  Required Terms:  
    Term 0:        kubernetes.io/hostname in [agents-2]
Message:           
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /var/vcap/store/k3s-local-storage-path/pvc-be1f270c-5699-4b50-a904-40a777e284ec_openldap_ldap-data-ldap-0
    HostPathType:  DirectoryOrCreate
Events:            <none>
```

### Affected releases

v50

**Comment by JCL38-ORANGE** [comment]
the persistent volume matching is now down at shield provisioning time. So if a namespace is recreated (new persistent volume), it is possible to reconfigure shield by triggering the job <concourse-url>/teams/micro-depls/pipelines/micro-depls-bosh-generated/jobs/run-errand-01-ci-k8s-shield-provisioning.
a custom script (master-depls/shieldv8/scripts/restore-ldap-k8s-data.sh) will be delivered in paas-templates in order to : 
- retrieve data (valid archive) from source persistent volume
- import it to target persistent volume
such script already exists in order to restore shield itself

**Comment by JCL38-ORANGE** [comment]
delivered in v51.
