### ISSUE TITLE
buildpack is invalid - stack unique

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1110]
### Expected behavior

* As a paas-templates operator
* In order to
  * install v50.0.1 and update cloudfoundry buildpack 
* I need 

### Observed behavior
master-depls/cf/terraform apply jobs fails with:

```
Error: Buildpack is invalid: stack unique

  on terraform-instructions.tf line 164, in resource "cloudfoundry_buildpack" "binary-buildpack-offline":
 164: resource "cloudfoundry_buildpack" "binary-buildpack-offline" {

```

context:
- versions
  - terraform bosh release 3.
  - cf deployment 15.5.0
  - cloudfoundry terraform plugin  0.13.0
  - reference for buildpack stack association https://docs.cloudfoundry.org/buildpacks/stack-association.html

- installed buildpacks
```

position   name                      stack        enabled   locked   filename
1          staticfile_buildpack      cflinuxfs3   true      false    staticfile_buildpack-cflinuxfs3-v1.5.14.zip
2          java_buildpack            cflinuxfs3   true      false    java-buildpack-cflinuxfs3-v4.35.zip
3          ruby_buildpack            cflinuxfs3   true      false    ruby_buildpack-cflinuxfs3-v1.8.27.zip
4          dotnet_core_buildpack     cflinuxfs3   true      false    dotnet-core_buildpack-cflinuxfs3-v2.3.19.zip
5          nodejs_buildpack          cflinuxfs3   true      false    nodejs_buildpack-cflinuxfs3-v1.7.37.zip
6          go_buildpack              cflinuxfs3   true      false    go_buildpack-cflinuxfs3-v1.9.23.zip
7          python_buildpack          cflinuxfs3   true      false    python_buildpack-cflinuxfs3-v1.7.26.zip
8          php_buildpack             cflinuxfs3   true      false    php_buildpack-cflinuxfs3-v4.4.27.zip
9          nginx_buildpack           cflinuxfs3   true      false    nginx_buildpack-cflinuxfs3-v1.1.19.zip
10         r_buildpack               cflinuxfs3   true      false    r_buildpack-cflinuxfs3-v1.1.11.zip
11         binary_buildpack          cflinuxfs3   true      false    binary_buildpack-cflinuxfs3-v1.0.36.zip
16         cached-static-buildpack                true      false    staticfile_buildpack-cached-v1.5.9.zip
16         cached-php-buildpack                   true      false    php_buildpack-cached-v4.4.19.zip
16         cached-java-buildpack                  true      false    java-buildpack-offline-v4.32.1.zip
16         cached-python-buildpack                true      false    python_buildpack-cached-v1.7.17.zip
16         cached-nodejs-buildpack                true      false    nodejs_buildpack-cached-v1.7.25.zip
17         cached-go-buildpack                    true      false    go_buildpack-cached-v1.9.15.zip
18         cached-binary-buildpack                true      false    binary_buildpack-cached-v1.0.36.zip
19         cached-ruby-buildpack                  true      false    ruby_buildpack-cached-v1.8.26.zip
```
 
installed cloudfoundry stacks (only one stack):

```
cf stacks
Getting stacks as poblin...

name         description
cflinuxfs3   Cloud Foundry Linux-based filesystem (Ubuntu 18.04)

```

### Affected releases

* 50.0.1

**Comment by gberche-orange** [comment]
This issue seems to be transient.

@poblin-orange My research below shows rather an error returned by CC cloud controller, possibly when an existing buildpack with same name exists without an assigned stack:

* Similated in CF CLI HTTP response mocks https://github.com/cloudfoundry/cli/blob/9a0a21542ceb383e18142df627432924a7a07d9e/cf/api/apifakes/old_fake_buildpack_repo.go#L90
```go
} else if repo.CreateBuildpackWithNilStackExists {
		return repo.CreateBuildpack, errors.NewHTTPError(400, errors.StackUnique, "stack unique")
}
```
* Likely in CC codebase around:
   * https://github.com/cloudfoundry/cloud_controller_ng/blob/60a2a9e30d/spec/unit/models/runtime/buildpack_lifecycle_data_model_spec.rb
   * https://github.com/cloudfoundry/cloud_controller_ng/blob/60a2a9e30dc6f743fb107592e898e83d6f0ee0c1/app/models/runtime/buildpack.rb#L39 `validates_unique [:name, :stack]`
   * https://github.com/cloudfoundry/cloud_controller_ng/blob/60a2a9e30dc6f743fb107592e898e83d6f0ee0c1/app/models/runtime/buildpack.rb#L75-L79 `errors.add(:stack, :unique) if Buildpack.exclude(guid: guid).where(name: name, stack: nil).present?`
* No specific logic in terraform provide codebase at https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/blob/master/cloudfoundry/resource_cf_buildpack.go
   * nor in http client https://github.com/cloudfoundry/cli/blob/9a0a21542ceb383e18142df627432924a7a07d9e/api/cloudcontroller/ccv2/buildpack.go#L77-L98

**Comment by poblin-orange** [comment]
This is about loading cached buildpack. I didnt find a way to specify stack with terraform cloudfoundry. Change from previous version is we dont specify position anymore. Might explain the transient failure.
To reopen if necessary (labeled as kb)
