### ISSUE TITLE
coab deployments prometheus metrics are lacking some labels: __meta_bosh_deployment, client osb platform, client service instance guid

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1407]
### Expected behavior

* As a paas-templates operator
* In order to leverage prometheus metrics (such as mysql nb of statement or tables/rows metrics) to identify under-used service instances
* I need coab prometheus metrics to include the following labels to correlate with client subscription 
   * the bosh deployment name (` __meta_bosh_deployment`)
   * the client osb platform (made available in osb-cmdb as `x-osb-cmdb.annotations.brokered_service_client_name`)
   * the client service instance guid (made available in osb-cmdb as `x-osb-cmdb.annotations.brokered_service_instance_guid`) 
   

### Observed behavior
 
`mysql_binlog_file_number{instance="192.168.61.86:9104",job="mysql",osb_client_cf_instance_name="mysql-gberche-v52_05",osb_client_cf_org_name="acdc-servicesbackend-staging",osb_client_cf_space_name="acdc-service-backend-int-space-scoped",osb_client_orange_annotation_basicat="xxx",osb_client_orange_annotation_orangecarto="12345"}`

### Root cause

Invalid syntax on relabel_configs:
https://github.com/orange-cloudfoundry/paas-templates-private/blob/9369581bbf55cf2b13242dfc585879cd615c406b/shared-operators/coab/monitoring-operators/82-add-monitoring-custom-addon-operators.yml#L41-L49

should use "drop" instead of "keep"

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
> <relabel_action> determines the relabeling action to take:
>  keep: Drop targets for which regex does not match the concatenated source_labels.
>  drop: Drop targets for which regex matches the concatenated source_labels.
> 

### Affected releases

* 52.x
* earlier versions

**Comment by JCL38-ORANGE** [comment]
Partially fixed in v53 : 
mysql_binlog_files{instance="192.168.61.86:9104",job="mysql",**meta_bosh_deployment="y_1402230d-481e-42a8-8eba-ad5358879b93"**,osb_client_cf_instance_name="mysql-gberche-v52_05",osb_client_cf_org_name="acdc-servicesbackend-staging",osb_client_cf_space_name="acdc-service-backend-int-space-scoped",osb_client_orange_annotation_basicat="ICL",osb_client_orange_annotation_orangecarto="26923",**osb_client_service_guid="54169b48-1bcd-45e5-bf03-97f92ca49b3b"}**

**Comment by gberche-orange** [comment]
client name is available as `x-osb-cmdb.annotations.brokered_service_client_name`

**Comment by JCL38-ORANGE** [comment]
Fixed in v53 : 
mysql_binlog_files{instance="192.168.61.86:9104",job="mysql",**meta_bosh_deployment="y_1402230d-481e-42a8-8eba-ad5358879b93"**,osb_client_cf_instance_name="mysql-gberche-v52_05",osb_client_cf_org_name="acdc-servicesbackend-staging",osb_client_cf_space_name="acdc-service-backend-int-space-scoped",**osb_client_name="cmdb-cf-z2-services"**,osb_client_orange_annotation_basicat="ICL",osb_client_orange_annotation_orangecarto="26923",**osb_client_service_guid="54169b48-1bcd-45e5-bf03-97f92ca49b3b"}**
