### ISSUE TITLE
ksqldb tests & lint for paas-templates topologies

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1731]
### Expected behavior

* As a paas-templates maintainer
* In order to detect regressions when making changes to ksqldb pipelines
* In order to produce living documentation of ksqldb processing
* I need to be protected by tests

### Observed behavior
 
Currently, the .sql include human-readeable sample data, but contain
* no unit tests against controlled data
* no end-to-end tests against current real data

#### test
* extract sample data from existing input topics https://docs.ksqldb.io/en/latest/how-to-guides/test-an-app/#generate-an-input-file-from-an-existing-topic
* capture sample output from existing output topics https://docs.ksqldb.io/en/latest/how-to-guides/test-an-app/#generate-an-input-file-from-an-existing-topic
* package as assertions using https://docs.ksqldb.io/en/latest/how-to-guides/test-an-app/ 
* schedule into a CI pipeline

#### query linting

https://github.com/thekiwi/ksql-lint

### Affected releases

* x.y
* earlier versions

**Comment by Guilamb** [comment]
## List of tables and streams to test
* service instance inventory
   * test when a service is created, updated and deleted
* bosh_deployment_inventory
* healthyJobs and unhealthyJobs
* service_instance_info_enriched_with_plan_name
* service_instance_info_enriched_with_service_label_and_plan_name
* service_instance_info_enriched_with_org_name
* BOSH_REVENUE_ASSURANCE
* service_instances_coab_with_bosh_deployments
* orphaned_service_instances_coab_wrt_bosh_deployments

**Comment by Guilamb** [comment]
KafkaCat, renamed kcat, is an external tool, not provided by any official confluent images.
https://github.com/edenhill/kcat
Two options come to my mind for now :
* Create a cronjob, using kcat image, in order to extract raw sample data and send it to another job for testing
* Create a cronjob with a custom image that includes every tool needed to generate a ready to use set of sample data and do tests.

**Comment by Guilamb** [comment]
# Method used to generate the tests

This method is a first draft and will change in the future.
We uses 2 different image : **confluentinc/ksqldb-cli:0.28.2** for interrogating ksqldb database, and **orange-cloudfoundry/ksql-test-docker:lates**t. The last one is a Kcat image with JQ added in order to format Kcat outputs.
On the local environment the only tool required is docker.

## 🔵 On KSQL-CLI Container

First we get the definition of the table or stream that we wanna test.
```DESCRIBE <object_name> EXTENDED;```
it will be under the Statement section.
With that we can constitute our Statements.sql file.

## 🔵 On KCAT Container
Using Kcat and JQ we will get a small part of desired Topic data, that will constitute our inputs.json file. It will generally be the parent stream/table's topic of our object.
```
kcat -b BROKER:PORT -t <TOPIC> -C -e -J  -X security.protocol=***** -X sasl.mechanism=****** -X sasl.username=********* -X sasl.password=******** -c 5 | jq --slurp '{inputs:[.[]|{topic:.topic,timestamp: .ts, key: .key, value: .payload|fromjson}]}'
 ```
It is then necessary to create a outputs.json file specifying the result you expect from the object.

## 🔵 On Local environment or any other environment

We will use docker in order to do our tests, we will use the confluentinc/ksqldb-cli:0.28.2 image, because it include ksql-test-runner tool.
```
docker pull confluentinc/ksqldb-cli:0.28.2
```
```
docker run confluentinc/ksqldb-cli:0.28.2 sleep infinity
```
```
docker cp statements.sql <ContainerId>:statement.sql
docker cp inputs.json <ContainerId>:inputs.json
docker cp outputs.json <ContainerId>:outputs.json
```
```
docker exec -it <ContainerId> /bin/bash
```
inside the container we can run our test :
```
ksql-test-runner -s statements.sql -i input.json -o output.json
```

**Comment by gberche-orange** [comment]
Status on 28/03/2023:
* [x] exploration of kcat and ksql-test-runner
* [x] sample unit tests for some tables
   * [ ] manual post processing of inputs (w.r.t. "val" value) to be clarified: was it a mistake ?
   * [ ] same number of messages in input / output
* [ ] study how to make tests self descriptive and whether they can play the role of living documentation
   * https://johnfergusonsmart.com/living-documentation-not-just-test-reports/
   * https://livebook.manning.com/book/specification-by-example/chapter-3/
* [ ] schedule automated execution of tests
   * [ ] ksql production sql statements should be executed by tests. Currently sql statements are duplicated
   * [ ] CronJob experiment: 
      * [ ] not yet running the ksql-test-runner command
      * [ ] clarify the exit status
   * [ ] Github workflow to feedback on the PR status
* [ ] granularity of test execution, and test summary/report

**Comment by gberche-orange** [comment]
We have pause our exploration project of ksqldb. Reopen if we resume in the future.
