### ISSUE TITLE
duplicate configuration issue on shield v8

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#293]
### Expected behavior
I expect the configuration is loaded once and exactly once in shield v8 used on coab-depls.  

### Observed behavior
It appears that the configuration (retention, storage, ...) is loaded multiple times. 

### Affected release
v39

### Traces and logs
Stderr     WARNING: ignoring the SHIELD Core set by either --core or the $SHIELD_CORE environment variable.  
	
           (shield import uses the import file to determine what SHIELD Core to contact.)  
	
             
	
           !!! <stdin>: unable to find storage system 'obosv4-cf-mysql' for 'mysql/2-full-daily' job on tenant 'cf-mysql': multiple matching stores found

**Comment by JCL38-ORANGE** [comment]
https://github.com/starkandwayne/shield-boshrelease/issues/163

**Comment by ldangeard-orange** [comment]
The problem comes from the import that throws multiple errand that loads the SHIELD parameters. With each parameter, SHIELD checks if the parameter exists to avoid duplicates. In some cases, the creations are made at the same time, and duplicates are created.

# workaround
Go back to the previous solution: Loop on all the nodes for the import shield
```sh
bosh -d <deployment-name> run-errand import --instance=INSTANCE-GROUP[/INSTANCE-ID] 
```

**Comment by poblin-orange** [comment]
fixed in v30
