### ISSUE TITLE
shared rabbit mq ha

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#436]
### Expected behavior
As a platform operator, i want to offer a clustered multi az p-rabbitmq, in order to be able to cope with the loss of a Iaas AZ

### Observed behavior
As of v41, the cluster and haproxy are single vm/az, and service binding return a single IP address.

The rabbitmq service binding include a single IP address. In case of loss of an AZ, the manual reparation is restoring the rabbitmq cluster (+ service broker) from backup on an healthy AZ, and unbind/rebind all service instances.

### references
- #410

**Comment by gberche-orange** [comment]
https://docs.pivotal.io/rabbitmq-cf/1-16/use.html mentions

The hostnames field in VCAP_SERVICES contains a single hostname, even if there is more than one RabbitMQ node. BOSH DNS resolves the hostname to a list of the IP addresses of all the available RabbitMQ nodes. The order of the IP addresses rotates so that there is load balancing.

A RabbitMQ client can use the first IP address returned. If a node becomes unavailable, BOSH DNS removes it from the list of resolved IP addresses. Because of this, apps should not cache the IP addresses of the nodes, as the cache might become outdated. The Java buildpack automatically disables DNS caching.

The broker would need to be configured to return a FQDN leveraging bosh DNS alias entry
https://github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release/blob/387e639a271664cc62ea04f2ead57056304758af/jobs/rabbitmq-service-broker/spec#L19-L20 
  rabbitmq-service-broker.rabbitmq.dns_host:
    description: "External load balancer host"

The FQDN will reference all rabbitmq healthy nodes on both AZs, similar to the the example on 
https://bosh.io/docs/dns/#example

**Comment by poblin-orange** [comment]
current limitations:
- bosh-dns is note shared between diego-cell (bosh-master) and rabbitmq vms (bosh-ops)
- if we want to expose the rabbit out of paas-templates, we cant rely on dns (yet)

**Comment by JCL38-ORANGE** [comment]
Merged in v43.
