### ISSUE TITLE
v41: default cf push should be cflinuxfs3

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#482]
### Expected behavior
As a platform operator, with paas-templates v40 / cf-deployment 7, i expect default stack for new cf push app to be cflinuxfs3

### Observed behavior
Seems the buildpack ordering overrides the cf-deployment configured default stack ?

### Affected release

Reproduced on version 41.0.2

**Comment by gberche-orange** [comment]
@poblin-orange I'm not reproducing the issue. A new app seems staged with cflinuxfs3 by default. See related documentation and steps I used to reproduce. Please let me know the steps used to reproduce the problem.

[Proposed Scope for CF-Deployment 7.0](https://lists.cloudfoundry.org/g/cf-dev/message/8409?p=,,,20,0,0,0::Created,,cf-deployment+7.0,20,2,0,28737846) points to [epic](https://www.pivotaltracker.com/epic/show/4116006) and [cf-linuxfs3 story](https://www.pivotaltracker.com/story/show/163037665)

> Scenario: new app associated with cflinuxfs3
> Given my acceptance env is running a plain vanilla deploy of the RC
> When I run `cf push dora`
> Then I can confirm
> 1. the app is successfully pushed
> 2. the cli response shows cflinuxfs3 as the stack
> 3. I see "Hi, I'm Dora!" when I load the app's route in my browser

Running this step, the output was matching the expected behavior:

```sh
echo "#random content" > Staticfile
echo "Hello world" > index.html
cf push hello-stacks
[...]
Waiting for app to start...

name:              hello-stacks
requested state:   started
routes:            hello-stacks.redacted-domain
last uploaded:     Mon 08 Jul 10:45:59 CEST 2019
stack:             cflinuxfs3
buildpacks:        staticfile

type:            web
instances:       1/1
memory usage:    512M
start command:   $HOME/boot.sh
     state     since                  cpu    memory      disk        details
#0   running   2019-07-08T08:46:04Z   0.0%   0 of 512M   0 of 512M   
```

**Comment by gberche-orange** [comment]
Cloudcontroller enables choosing the default stack at the platform level 
https://bosh.io/jobs/cloud_controller_ng?source=github.com/cloudfoundry/capi-release&version=1.79.0#p%3dcc.default_stack
> The default stack name to use if no custom stack is specified by an app.
> Default
> cflinuxfs3

The default stack is used in paas-templates v41, and we therefore observe in `master-depls/cf/cf.yml`

```yml
        default_stack: cflinuxfs3
```

Tracing which capi version is used in v41: 
https://github.com/cloudfoundry/cf-deployment/tree/v7.11.0 
https://github.com/cloudfoundry/cf-deployment/blob/v7.11.0/cf-deployment.yml#L2345-L2348

**Comment by poblin-orange** [comment]
The default stack applies for NEW cf apps.
closing as 41.0.2 is ok
