### ISSUE TITLE
add support for offline buildpack

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#5]
### Expected behavior

cf community does not provide offline buildpack anymore - cf 264
Runner expect to be able to specify their own buildpacks in paas-templates  (including community BP rebuild for offline )

### Observed behavior
Currently, only online buildpack are provided out-of the box.
Upgraded deployment keep offline buildpacks (like java_buildpack), but new bootstrapped deployment miss them (not anymore included)

### Affected release
v34

### reference
see:
-  discussion in https://lists.cloudfoundry.org/g/cf-dev/topic/what_s_wrong_with_buildpacks/6334179?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,80,6334179
 - https://cloudfoundry.slack.com/archives/C02HWMDUQ/p1542815669082700

### solution outline

We do not want to provide a solution to pull community buildpack and build them. Each runner and security teams can have a different policy for that.

solution design:
- [x] offer a way in cf-ops-automation to include raw concourse pipelines
- [x] base process in https://docs.run.pivotal.io/buildpacks/depend-pkg-offline.html#package-local
- [x] include in paas-templates the following pipeline as a git submodule https://github.com/orange-cloudfoundry/ci-buildpack-cached, with the s3 operator targeting private s3
- [x] add terraform instruction to upload buildpacks from private s3, offline buildpack should replace bsoh-release provided non cached buildpacks

**Comment by poblin-orange** [comment]
also, upgrading to java_buildpack 4.x requires to scale up java cf apps to 1G memory.

**Comment by o-orand** [comment]
We have integrated [ci-buildpack-cached](https://github.com/orange-cloudfoundry/ci-buildpack-cached) to build offline builpack

**Comment by gberche-orange** [comment]
Reopening since offline buildpacks are indeed constructed, but not yet leveraged in cf and internet-isolation-segment bosh deployment.

Usage of non cached buildpack is breaking one of our project which is setting http_proxy variable in his apps which is interfering with buildpack dependency fetching.

Workaround: set a no-proxy environment variable excluding online hosts. See related support in java-buildpack https://github.com/cloudfoundry/java-buildpack/search?q=no_proxy&unscoped_q=no_proxy and https://github.com/cloudfoundry/java-buildpack/issues/438

We would still leave the internet http_proxy staging evg group, which would only be usefull for fully online buildpacks

**Comment by poblin-orange** [comment]
closing this issue for now builds are ok.
