### ISSUE TITLE
terraform credhub managed properties do not support update

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#53]
### Expected behavior
When changing a password / value in credhub (with credhub cli or with credhub-importer bosh release), operators expect that the terraform construct retrieve the updated value

### Observed behavior

After credhub, update, terraform credhub still return old value

### Affected release

Reproduced on version x.y
v24

### Traces and logs

related upstream issue
- https://github.com/orange-cloudfoundry/terraform-provider-credhub/issues/2

**Comment by gberche-orange** [comment]
* [ ] code review on the provider side. 
   * The credhub_value datasource is quite simple and does [a straight fetch](https://github.com/orange-cloudfoundry/terraform-provider-credhub/blob/40a0d2450b9ee74f75abd7ab50b98a3761d9ae19/resources/data_sources.go#L48-L64) from credhub using credhub cli code [](https://github.com/orange-cloudfoundry/terraform-provider-credhub/blob/master/vendor/github.com/cloudfoundry-incubator/credhub-cli/credhub/get.go#L31-L36) which in turns calls [getCurrentCredential](https://github.com/orange-cloudfoundry/terraform-provider-credhub/blob/master/vendor/github.com/cloudfoundry-incubator/credhub-cli/credhub/get.go#L100-L105) whick asks for the latest [1 value in the api](https://credhub-api.cfapps.io/#get-by-name)
   * The latest credhub CLI code [specifies](https://github.com/cloudfoundry-incubator/credhub-cli/blob/fbeb23df0fb050ff5cfaf4d0a8de33942cd00d9e/credhub/get.go#L100-L107)  the current=true option instead of the versions=1 in the [get-by-name](https://credhub-api.cfapps.io/#get-by-name) credhub api call
   * [ ] browse the credhub client code history and credhub server history
      * Seem the issue comes from the fact that the versions flag is only supported since credhub server v1.4.0+ whereas we're still on 1.0.2. See related [story 150657845](https://www.pivotaltracker.com/n/projects/1977341/stories/150657845) which mentions `[versions flag] currently only works with server v1.4.0+`
   * [ ] reproduce and debug the issue 
      * [ ] add debug traces to the provider to display credhub response
      * [ ] MITM the credhub response
* [ ] Bump credhub server version in paas-template. [1.0.2](https://github.com/pivotal-cf/credhub-release/releases/tag/1.0.2) is almost a year old (Jun 30, 2017)
* [ ] Bump the credhub cli version in

**Comment by poblin-orange** [comment]
fixed in v37
