### ISSUE TITLE
NFS performance limited

### ISSUE THREAD

**Issue by T0FFF** [orange-cloudfoundry/paas-templates#538]
### Expected behavior

The writing speed should be the same (or almost) in CF apps and in a direct NFS mount on a VM. In the CF apps, the performances are very bad.

### Observed behavior
* From a VM on the NFS mount:
wget https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-edu-10.0.0-amd64-netinst.iso
...
debian-edu-10.0.0-amd64-netinst.iso    100%[==========================================================================>] 404.00M  **26.9MB/s**    in 15s

* FROM a cf apps:
o	On the container : 
vcap@2cd390f9-7d5d-4c04-5456: ~ /app $ wget https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-edu-10.0.0-amd64-netinst.iso
10% [==========>           
                                                                                   ] 44,580,864  **35.8MB/s**   in 1.2s   
o	On the NFS mount :
vcap@2cd390f9-7d5d-4c04-5456: ~ /app/uploads $ wget https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-edu-10.0.0-amd64-netinst.iso
0% [                                                                                                         ] 3,727,360    **744KB/s**

### Affected release

nfs-volume: 1.5.3 -> 1.7.4
mapfs: 1.1.0 -> 1.2.0

**Comment by gberche-orange** [comment]
Further diagnostics using dd command to not depend on wget to fetch data over the network and avoid variations linked to download times, indicates that the problem seems to be with fuse-nfs and not diego/garden process cpu/io throttling. Seems the nfs-fuse is very slow to exchange with the nfs server

Next steps:
* diagnostics
   * try tcpcump and wireshark analysis on the fuse-nfs process to diagnose network-level problems
   * ask support to the CF persi team in cf slack [#cf-volume-services](https://app.slack.com/client/T02FL4A1X/C0K0JF319/details/info)
* potential fixes
   * bump the nfs-volume bosh release in master-depls-version from "1.5.3" to currently used cf-deployment version. Latest cf-deployment uses "2.3.0" see https://github.com/cloudfoundry/cf-deployment/blob/5f5b327ad6d1e9a4d72f1bc9eeea7e7cd20f51d8/operations/enable-nfs-volume-service.yml#L159-L165

Following are related diagnostics performed this morning with @poblin-orange 
-----

From NFS volume mounted on the diego cell directly in /tmp/nfs
```
diego-cell/9ffe53eb-5ef3-4816-a595-791223883c0d:/var/vcap/data/volumes/nfs/c54cc196-c87f-47da-8f82-f892e39ae75d-02b153f395400b7b0883d5f6de78e9db
$ dd if=/dev/zero bs=10MB of=/tmp/nfs/benchmark-from-nfs-mount
 
dd: error writing '/tmp/nfs/benchmark-from-nfs-mount': Disk quota exceeded
3146+0 records in
3145+0 records out
31450000000 bytes (31 GB, 29 GiB) copied, 72.1545 s, 436 MB/s
$ rm /tmp/nfs/benchmark-from-nfs-moun
```

From diego cell using the fuse-nfs mount, outside of the container:
```
$ dd if=/dev/zero bs=300MB count=1 oflag=direct of=/var/vcap/data/volumes/nfs/c54cc196-c87f-47da-8f82-f892e39ae75d-02b153f395400b7b0883d5f6de78e9db/bench-from-diego-fuse
1+0 records in
1+0 records out
300000000 bytes (300 MB, 286 MiB) copied, 64.4539 s, 4.7 MB/s
```

Syscalls on the fuse-nfs process, show very slow system calls

```
fuse-nfs -a -n nfs://[.redacted-nfs-host-name.]/share-2e561f52?uid=0&gid=1000 -m /var/vcap/data/volumes/nfs/c54cc196-c87f-47da-8f82-f892e39ae75d-02b153f395400b7b0883d5f6de78e9db --auto_cache
```

![image](https://user-images.githubusercontent.com/4748380/65235284-90e08300-dad6-11e9-985c-5f73e98293d8.png)

Displaying fuse-nfs io and disk stats did not really help

![image](https://user-images.githubusercontent.com/4748380/65241219-4fa2a000-dae3-11e9-93ff-fc8560c97975.png)

Related doc on how to use htop to display full process arguments (scroll right), display iostat
* https://serverfault.com/questions/392191/how-to-get-iostat-of-a-single-process
* https://unix.stackexchange.com/questions/158839/how-to-configure-htop-to-display-the-complete-command-line
* https://www.softprayog.in/tutorials/htop-command-in-linux
