### ISSUE TITLE
pwm automation broken

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#67]
### Expected behavior
Once pwm cf apps is deployed, operators should be able to cf restage the app.

### Observed behavior
The pwm artifact is download online for pwm site. Builds are regularly cleaned. This breaks the automation

Problem occurs with numeric value (ie: cf_ssh_port).
Workaround is to add double quote around the value eg "80", not 80.

### Affected release

Reproduced on version v 27

**Comment by JCL38-ORANGE** [comment]
**Action plan :** 

- Short term : Fix the problem in a feature branch in order to use a new release (2018-05-16T18_58_17Z)

- Long term : 

- [ ] Fork the pwm github repository (https://github.com/pwm-project/pwm) in orange-cloudfoundry organization 
- [ ] Create a concourse pipeline which aims to build (maven) the war/jar artifacts and to publish these binaries to minio private S3 (build pack pipeline reference for a such pipeline)

**Comment by poblin-orange** [comment]
new offline replication concourse pipeline should support this offline build

**Comment by poblin-orange** [comment]
as of v40, a static aws s3 replicat of the pwm artifact has been set, and documented.
postponing full resolution to 41; with a discuss flag :  corporate ldap might use lemon-ldap ng, we should investigate if it can replace pwm

**Comment by poblin-orange** [comment]
NB: hotfix applied on v38

**Comment by obeyler** [comment]
PWM is not present anymore inside paastemplate
