### ISSUE TITLE
missing shield backup for cfcr master and coab/k8s-serv

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#776]
### Expected behavior

* As a paas-templates operator
* In order to be able to restore in case of failure
* I need the cfcr etcd to be backuped with shield

### Affected releases

* x.y
* earlier versions

**Comment by obeyler** [comment]
should be made inside /share-operator/cfcr then call deployOnEachCfcr.sh

**Comment by JCL38-ORANGE** [comment]
done for cfcr master, waiting end of refactoring for kubo-depls.

**Comment by JCL38-ORANGE** [comment]
https://github.com/cloudfoundry-incubator/kubo-disaster-recovery-acceptance-tests/blob/master/README.md

**Comment by JCL38-ORANGE** [comment]
merged in v47

**Comment by gberche-orange** [comment]
K8S master node data stored in etcd seem to require an etcd builtin backup see https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#backing-up-an-etcd-cluster

Quick overview of apparent opensource automation of etcd backup and restore
* coreos [etcd operator](https://github.com/coreos/etcd-operator), [docs](https://coreos.com/operators/etcd/docs/latest/user/walkthrough/backup-operator.html), [has been archived](https://github.com/coreos/etcd-operator/pull/2169)
* [Kops - Kubernetes Operations](https://kops.sigs.k8s.io/) has built in support for [etcd backup and restore](https://kops.sigs.k8s.io/operations/etcd_backup_restore_encryption/) to S3. This seems however to require installation of ectd through [etcd-manager](https://github.com/kopeio/etcd-manager). See [usage of etcd-manager within kops for etcd backup & restore](https://kops.sigs.k8s.io/operations/etcd_backup_restore_encryption/)
   * Kops has openstack support
   * Kops vsphere support was [removed](https://github.com/kubernetes/kops/issues/9166) in 2020 in favor of vmware tanzu closed source investments
* [Velero](https://velero.io/docs/main/index.html) . 
> Velero treats object storage as the source of truth. It can continuously check to see that the correct backup resources are always present. If there is a properly formatted backup file in the storage bucket, but no corresponding backup resource in the Kubernetes API, Velero synchronizes the information from object storage to Kubernetes.
   * https://velero.io/docs/main/api-types/schedule/ The Schedule API type is used as a repeatable request for the Velero server to perform a backup for a given cron notation. Once created, the Velero Server will start the backup process. It will then wait for the next valid point of the given cron expression and execute the backup process on a repeating basis.

   * https://velero.io/docs/main/faq/
> When is it appropriate to use Velero instead of etcd’s built in backup/restore?
> 
> Etcd’s backup/restore tooling is good for recovering from data loss in a single etcd cluster. For example, it is a good idea to take a backup of etcd prior to upgrading etcd itself. For more sophisticated management of your Kubernetes cluster backups and restores, we feel that Velero is generally a better approach. It gives you the ability to throw away an unstable cluster and restore your Kubernetes resources and data into a new cluster, which you can’t do easily just by backing up and restoring etcd.
> 
> 
> Examples of cases where Velero is useful:
> 
>     you don’t have access to etcd (e.g. you’re running on GKE)
>     backing up both Kubernetes resources and persistent volume state
>     cluster migrations
>     backing up a subset of your Kubernetes resources
>     backing up Kubernetes resources that are stored across multiple etcd clusters (for example if you run a custom apiserver)

> 


Velero was integrated as part of v44. 

Currently apparently fails in v47.0.2 with restic pods failing to reach K8S API

> Get "https://10.245.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%3D1ae93daf-fbbd-47bf-bf79-6d0f440d2684.k8s%2Cstatus.phase%3DRunning": Service Unavailable                         │
│ stream closed          

No backup resources are available in K8S inventory.
Since prometheus metrics are enabled, might be worth checking failed backup metrics, and set up alerting
