### ISSUE TITLE
COA 5 post migration cleanup

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#825]
### Expected behavior

* As a paas-templates maintainer
* In order to have a clean codebase after COA 5 migration
* I need to clean
  - [X] root-deployment deploy.sh (most releases are now managed with root-deployment.yml, including bosh runtime required releases). We should only keep the non repackagable releases (eg: weave-scope, kubo orange release)
  - [X]  legacy root deployment xx-versions.yml files (replaced by root-deployment.yml)
  - [ ] bosh ops file reseting the release version to 'latest'. This is now useless, COA 5 will replace versions in manifest, disregarding manifest file version (in a new COA concourse task). This is for community provided bosh manifest (eg: master-depls/cf, master-depls/logsearch, kubo, prometheus bosh releases)

==> issue with sha1 provided (cf-deployment sets sha1)

### Affected releases

* 48.0.0

**Comment by o-orand** [comment]
Implemented:
 - [x] root-deployment `deploy.sh`
 - [x] legacy root deployment xx-versions.yml files

**Comment by o-orand** [comment]
@poblin-orange I've tried to remove operator overriding version with latest. Unfortunately, we have an issue with existing sha1. As we repackage boshreleases, sha1 does not match expecting one. So instead of updating all operators, I think we can keep existing operator setting version to 'latest' (it will remove sha1 definition as side effect). 
As it was the last todo, I propose to close this issue.
