### ISSUE TITLE
coab mongodb and redis metrics not collected

### ISSUE THREAD

**Issue by gcordierOrange** [orange-cloudfoundry/paas-templates#925]
### Expected behavior

* As a paas-templates operator 
* In order to have a dashboard for monitoring redis coab
* I need to collect metrics from redis coab

### Observed behavior
No metrics are collected, but redis exporter are deployed with the service.
 
### Affected releases

* 47.0.3

**Comment by JCL38-ORANGE** [comment]
It is related to https://github.com/orange-cloudfoundry/paas-templates/issues/861.
Since 47.0.3, there is a CIDR filter (type = allow only) on bosh-exporter with value 192.168.0.0/16.
Metrics are collected only if the VM IP matches this CIDR (it is the case for mariadb and cf-rabbit).
MongoDB and redis exporters are hosted on public IP, so the metrics are no more collected.

**Comment by poblin-orange** [comment]
my bad :-(

**Comment by JCL38-ORANGE** [comment]
the architecture with both public and private IP is not possible with the current brokers implementation. Indeed, the binding returns the private IP and not the public IP.

**Comment by JCL38-ORANGE** [comment]
I think it is a possible to solve this without changing the architecture. Indeed, we plan to add an embedded prometheus on each dedicated services. This embedded prometheus will be configured without CIDR filtering so it will be able to gather metrics both on private and public IPs. 
Each embedded prometheus will be federated to prometheus exporter COAB.
